### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by Sundowndev** [skavngr/rapidscan#1]
A docker image with all the tools pre-installed would be awesome

**Comment by 5UP4F15H** [comment]
docker pull kalilinux/kali-linux-docker

**Comment by sh4nx0r** [comment]
@Sundowndev, Please have a look at this post.
https://medium.com/@airman604/kali-linux-in-a-docker-container-5a06311624eb

Hope this resolves this issue. If not, feel free to reopen it.
