### ISSUE TITLE
A problem in the Dockerfile

### ISSUE THREAD

**Issue by benhacka** [skavngr/rapidscan#10]
First, I would like to thank you for the script. Many thanks! Amazing work.

With use the current version of Dockerfile, we cant build our own image, because we can see an error (and this is pretty essential addiction):
`E: Unable to locate package golismero`

You need to add a non-free repo to the Dockerfile - edit current Dockfile like this for example:

```
FROM kalilinux/kali-rolling
RUN echo "deb http://old.kali.org/kali sana main non-free contrib" >> ./etc/apt/sources.list
RUN apt-get update && apt-get -yu dist-upgrade -y
# etc
```

After updating with non-free repo, all work fine.

**Comment by sh4nx0r** [comment]
Appreciate if you could initiate a PR and I shall merge it with the main branch.

**Comment by filebe777** [comment]
File "./rapidscan.py", line 109
    print bcolors.BOLD+"Vulnerability Threat Level"+bcolors.ENDC
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(bcolors.BOLD+"Vulnerability Threat Level"+bcolors.ENDC)?
