### ISSUE TITLE
Upgrading to Python 3

### ISSUE THREAD

**Issue by najum98** [skavngr/rapidscan#18]
Hello!

I really liked your tool, you surely have put a lot of effort into this tool, and I see that the development is still under progress. Don't you think that it will be a better idea to shift this tool to Python 3 as this is the future. Python 2 is deprecating with the passage of time. If you're willing to make the transition, I can work with you, we can together make the proper changings to shift from Python 2 to Python 3. Waiting for your thoughts on it. Thanks

**Comment by sh4nx0r** [comment]
Hi @najum98,

If you are really interested, appreciate if you can create a separate branch and work on it. After enough testing, we can merge it to the main branch.
