### ISSUE TITLE
fierce unrecognized arguments: -dns

### ISSUE THREAD

**Issue by drat-lab** [skavngr/rapidscan#19]
I got unrecognized -dns arguments error.

Fierce Subdomains Bruter - Brute Forces Subdomain Discovery.
------------------------

usage: fierce [-h] [--domain DOMAIN] [--connect] [--wide]
              [--traverse TRAVERSE] [--search SEARCH [SEARCH ...]]
              [--range RANGE] [--delay DELAY]
              [--subdomains SUBDOMAINS [SUBDOMAINS ...] | --subdomain-file
              SUBDOMAIN_FILE] [--dns-servers DNS_SERVERS [DNS_SERVERS ...] |
              --dns-file DNS_FILE] [--tcp]
fierce: error: unrecognized arguments: -dns example.com

**Comment by Epoch1331** [comment]
me too

**Comment by sh4nx0r** [comment]
Thank you @drat-lab & @Epoch1331. The issue has been fixed.

**Comment by droe001** [comment]
can you help me I'm having problems with the fierce tool I get this fierce: error: unrecognized arguments:
