### ISSUE TITLE
Finding vulnerable domain

### ISSUE THREAD

**Issue by ratpunk2** [skavngr/rapidscan#21]
Hi I am using this awesome tool from last two days but still can't figure out how do I find the vulnerable domain/subdomain . I mean I get few critical vuln notification when testing a domain can't find which subdomain/parameter is vulnerable Rapidscan only showing the warning but not the vulnerable url/parameter. 

Can you please help?

**Comment by sh4nx0r** [comment]
@ratpunk2 , Once the scan completes, kindly check the **RS-Vulnerability-Report** under the same directory to verify and validate the vulnerability.
