### ISSUE TITLE
Possibility to disable some tools

### ISSUE THREAD

**Issue by tristanlatr** [skavngr/rapidscan#22]
Hi,

I've been running into issues with `DMitry`, the scan takes more than 48h, which is not acceptable.  

I was wondering if there is an option to disable a specific tool using the rapidscan docker container ?

Thanks

**Comment by sh4nx0r** [comment]
Hello @tristanlatr , you can always use Ctrl+C to cancel the scan from a particular tool if it takes more time than usual.

**Comment by tristanlatr** [comment]
No I can't interact with the runner server while the scan is running, This tickets ask for a CLI options to disable a tool by name.

**Comment by tristanlatr** [comment]
Hi @sh4nx0r,

Could you re-open this ticket considering that it asks for a new CLI option. 

Perhaps something like `--skip <toolName>` ?

Thanks
