### ISSUE TITLE
Update Dockerfile for python 3

### ISSUE THREAD

**Issue by tristanlatr** [skavngr/rapidscan#31]
Thanks for the python 3 update.

The docker file should be updated and tested as well, I haven’t tested whether it currently works, but it looks like python3 is not installed, so I think the Dockerfile is currently broken.

**Comment by tristanlatr** [comment]
Also the docker image in the docker hub should be updated.

**Comment by sh4nx0r** [comment]
@tristanlatr thank you for re-opening it.

**Comment by Quentinchampenois** [comment]
Hi, I used the docker image and saw that it's broken.
I fixed it so I can suggest a PR asap if you are interested

**Comment by tristanlatr** [comment]
@kyuceee Yes please.

**Comment by tristanlatr** [comment]
Do you have control on the [`kanolato/rapidscan`](https://hub.docker.com/r/kanolato/rapidscan) docker hub image @sh4nx0r ?

I would not recommend users to use this image since it's not been updated for two years now.

**Comment by sh4nx0r** [comment]
@tristanlatr You can update the readme to match your repo.
