### ISSUE TITLE
unique output file names

### ISSUE THREAD

**Issue by zenfish** [skavngr/rapidscan#35]
stomping over the same file with all sorts of results... well... not even worth a pull request... but I added a few lines to disambiguate them - the main bit is:

`
date = subprocess.Popen(["date", "+%Y-%m-%d.%s"],stdout=subprocess.PIPE).stdout.read()[:-1].decode("utf-8")
debuglog  = "rs.dbg.%s.%s" % (target, date)
vulreport = "rs.vul.%s.%s" % (target, date)
`

That will create files that look like "rs.vul.google.com.2022-01-03.1641255361" or w/e.

I'd also advocate creating a vulnerability file even if nothing was found; e.g. change this:

`
if len(rs_vul_list)==0:
        print("\t"+bcolors.OKGREEN+"No Vulnerabilities Detected."+bcolors.ENDC)
`

To be a `report.write(*)` with the same text or w/e (not blank, since it could die in mid run and you wouldn't know if it really was zero vuls or not.)  First time I ran it I wasn't sure if there was a bug or what, since no result file was created.

YMMV, IMHO, etc.

**Comment by tristanlatr** [comment]
Sending an actual PR would be good.

**Comment by luisjmoreno** [comment]
First off, great tool, thank you extremely helpful! 

@sh4nx0r or @tristanlatr just wondering if there are any updates on this recommendation.  It be really great to have reports that display RS-*_servername_date.  

Thank you,

**Comment by tristanlatr** [comment]
This is a good recommendation and I would be happy to see a PR that fixes this issue.

**Comment by bhaveshraj336** [comment]
@sh4nx0r @tristanlatr  #45 i have made a pull request for these issue
