### ISSUE TITLE
scanning tool unavailable even if it available

### ISSUE THREAD

**Issue by ringawy** [skavngr/rapidscan#4]
![Screenshot_2019-08-24-01-33-54-96](https://user-images.githubusercontent.com/18529940/63628940-e892e800-c617-11e9-8f27-2dc18bb07af0.png)

I have nikto dimtry sslyze dnsrecon and golismer and other tool the script rapid scan still tell me that tool unavailable above script and on scan progress??

**Comment by sh4nx0r** [comment]
Which Operating System are you @ringawy are using?

**Comment by MuteAll** [comment]
i have the same issue , please tell us how can we install those tools or how to fix it . 
i also have some of those tools which i cloned them from github . but rapidscan cant recongnize and use them from directories . 
helps please :((

**Comment by Bitt3r** [comment]
It is very likely you didnt install everything properly, dont use root user, setup admin or normal user that will be sudoer. You can do that in terminal while using root user.
If this is still the problem, please send me logs and repository names in your system.

**Comment by Taguar258** [comment]
You probably need to install them into the bin folder.
