### ISSUE TITLE
Invalid google source in The Harvester email scan

### ISSUE THREAD

**Issue by victorgawk** [skavngr/rapidscan#49]
Test Case: The Harvester - Scans for emails using Google's passive search

The command `theHarvester -l 50 -b google -d URL` results in the following error because the `google` source is invalid: 
```
[!] Invalid source.
```

https://github.com/skavngr/rapidscan/blob/cb5ea0ed9264a775044228a82870f65c58f99784/rapidscan.py#LL512C1-L512C1

**Comment by bhaveshraj336** [comment]
@sh4nx0r  close this issue as it has been resolved in #50
