### ISSUE TITLE
Update tool not recognizing

### ISSUE THREAD

**Issue by Bitt3r** [skavngr/rapidscan#5]
Good day,
I wanted to do push for your code cause harvester is not working on latest Kali because of the name. So here you go the code, you can review it and make push. 
Its not big modification but theharvester is now theHarvester, if you go with theharvester it will tell you bash command not found. 

line 216 ["theHarvester","The Harvester - Scans for emails using Google's passive search.","theHarvester",1],
line 301  ["theHarvester -l 50 -b google -d ",""],
line 665 	["wapiti"], ["whatweb"], ["nmap"], ["golismero"], ["host"], ["wget"], ["uniscan"], ["wafw00f"], ["dirb"], ["davtest"], ["theHarvester"], ["xsser"], ["dnsrecon"],["fierce"], ["dnswalk"], ["whois"], ["sslyze"], ["lbd"], ["golismero"], ["dnsenum"],["dmitry"], ["davtest"], ["nikto"], ["dnsmap"]
line

**Comment by sh4nx0r** [comment]
@Bitt3r , Thank you for finding the bug. The code repository has been updated.

**Comment by Bitt3r** [comment]
@sh4nx0r You're welcome, will look it in detail and get back to you if I find anything to improve, modify etc.

**Comment by sh4nx0r** [comment]
@Bitt3r Appreciated :)
