### ISSUE TITLE
Running on Windows

### ISSUE THREAD

**Issue by Sobia-fayyaz** [skavngr/rapidscan#51]
Hello,

Can someone please guide me how can I run this successfully on windows?
After running it, I'm seeing a bunch of output files but all stating batch file issues.
I looked into docker file and see that I should install few other tools first but need assistance how can I do that on windows without impacting my system.

![error](https://github.com/skavngr/rapidscan/assets/18595075/c09fdf38-b594-4ae9-9bbd-472d79486cb1)

Thanks

**Comment by tristanlatr** [comment]
Simply don’t run it on windows: just use Kali Linux… I don’t think that maintainers will take the burden of making it work on windows.
