### ISSUE TITLE
rapidscan.py Program has error in line 805

### ISSUE THREAD

**Issue by theredteamhacker** [skavngr/rapidscan#7]
This is an excellent project thanks for making this project available for public.

when I run this program I got the following error .

Traceback (most recent call last):
  File "./rapidscan.py", line 805, in <module>
    rs_tool_output_file = open(temp_file).read()
IOError: [Errno 2] No such file or directory: 'temp_nikto_headers'

Iam using kali linux 2017.2 in VM ware virtual machine.
![Screenshot (264)](https://user-images.githubusercontent.com/59178742/71420055-0a20e080-2699-11ea-97ce-d652a4315d03.png)

**Comment by theredteamhacker** [comment]
Now this problem got solved.
I encountered this error when I tried to run this script in two terminals at a time.
When I use this script in only one terminal it works as usual.

**Comment by NeerajSec101** [comment]
\rapidscan\rapidscan.py", line 1442, in <module>
    logo()
  File "F:Pentesting\rapidscan\rapidscan.py", line 174, in logo
    print(logo_ascii)
  File "C:\Users\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u25cf' in position 97: character maps to <undefined>

**Comment by bravomanel** [comment]
> \rapidscan\rapidscan.py", line 1442, in logo() File "F:Pentesting\rapidscan\rapidscan.py", line 174, in logo print(logo_ascii) File "C:\Users\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode return codecs.charmap_encode(input,self.errors,encoding_table)[0] UnicodeEncodeError: 'charmap' codec can't encode character '\u25cf' in position 97: character maps to

I got the same error

**Comment by Lrt4i20** [comment]
Consigo executar o script dando skip no nmap e no dirb exemplo ./rapidscan.py URL --skip nmap --skip dirb
